FROM node:20-alpine

WORKDIR /app

# Install OpenSSL for Prisma
RUN apk add --no-cache openssl

# Copy package files
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Generate Prisma Client
COPY server/prisma ./prisma
RUN npx prisma generate

EXPOSE 4000

CMD ["npm", "run", "dev"]
